blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://discord.gg/refine
    about: If you have any doubts related to the project or want to discuss something, then join our Discord server
