name: Pull Request Previews

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    paths:
      - "packages/**"
      - "examples/fineFoods/**"

jobs:
  antd-fine-foods:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
          npm run bootstrap -- --scope fine-foods
          npm run build -- --scope fine-foods
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './examples/fineFoods/admin/antd/build'
          github-token: ${{ secrets.PANKOD_BOT_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          alias: deploy-preview-antd-${{ github.event.number }}
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          github-deployment-environment: "deploy-preview-antd-${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
  mui-fine-foods:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
          npm run bootstrap -- --scope mui-fine-foods
          npm run build -- --scope mui-fine-foods
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './examples/fineFoods/admin/mui/build'
          github-token: ${{ secrets.PANKOD_BOT_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          alias: deploy-preview-mui-${{ github.event.number }}
          enable-pull-request-comment: false
          overwrites-pull-request-comment: false
          github-deployment-environment: "deploy-preview-mui-${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10